controller:
  serviceType: LoadBalancer
  installPlugins:
    - kubernetes:4218.v1547.v4d52f9543
    - workflow-aggregator:596.v83260
    - git:5.2.0
    - configuration-as-code:1775.v810dc950b528
    - pipeline-stage-view:2.34
serviceAccount:
  create: true
  name: jenkins
