apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  APP_ENV: "production"
  POSTGRES_HOST: {{ .Values.db.host | quote }}
  POSTGRES_PORT: {{ .Values.db.port | quote }}
  POSTGRES_NAME: {{ .Values.db.name | quote }}
  POSTGRES_USER: {{ .Values.db.user | quote }}
