image:
  repository: lesson-7-django-repo
  tag: 'latest'
  pullPolicy: IfNotPresent
  registry: '842303507369.dkr.ecr.eu-west-1.amazonaws.com'

service:
  type: LoadBalancer
  port: 80

config:
  ALLOWED_HOSTS: '*'
  DEBUG: 'True'

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
